import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "./header/page";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

// Import Roboto with various weights
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Adjust weights as needed
  variable: "--font-roboto", // CSS variable for custom styling
});

export const metadata: Metadata = {
  title: "Create Next App2",
  description: "Generated by create next ap2222",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body>
        <Testing></Testing>{" "}
      </body> */}
      <body className={`${roboto.variable}`}>
        <div className="header">
          <Header></Header>
        </div>
        <div className="content">
          {/* <div>
            <Sidebar></Sidebar>
          </div> */}
          <div className="childrenContainer">{children}</div>
        </div>
        <div className="footer"></div>
      </body>
    </html>
  );
}
